version: "3.9"
services:
  server:
    build:  ./backend
    ports: 
    - "5000:5000"
    volumes: 
    - ./backend:/app
    environment: 
      FLASK_ENV: development
  web:
    build: ./invoice-frontend
    ports: 
      - "3000:3000"
    volumes: 
      - ./invoice-frontend:/user/src/app
    depends_on: 
      - server